language: python
python:
- "3.4"
env:
- TOXENV=py27
- TOXENV=py34
- TOXENV=pep8
before_install:
- pip install -U coveralls pip pytest pytest-cov setuptools wheel tox
script:
- tox
after_success:
- coveralls
notifications:
  slack:
    secure: o2NlD7CY5u12fw1ezIvZXRDg4i6yej1rcxx3OdgT95ELhFJfAGX/eRuZQDebc1oH4Sk0j1a62unE1yJJFepJI0XMHNuxVlUX0hWV+jJmxIJE/x6PljEqJIzByeMuWbxiokBowH/oHLKuHeXVqpK0ZzKQygwnNmQjrAPobugFioRaO9xp5T2aw6UrUFRyDxE0XZLaMMbg3oYxvlvPwm95MtZZWavMgLDg7sksa+7oADCSmdNPhisz23Ux6ZY8VZyk17vnl3SORc6a1FQiinU63503Au1rW695WfbR5f2hQDoP4pNES3SwNwF9sm6QAotJzkBjNKPHjslWkJ1kPjshYwW6BfOb/5MsDagHL9/8cJLAZPvqyScvDKHZjSsyk0ZIcGLwXCXHOjj62YVPKgaBuYb3ZrVfQiuhXJHlT2fuEikhSDcE4Z9wJafxxmBAdXS0TL4aA/ieUYdVH6mMSteIe+93nvi5VHa2Ip7SNDQ0M/JwpdIRx0UYlAd7tN8VNwCR013rfXqVEdEOnfvXiWhSAMsxbikxU1CrTdC7SKHtq0ha+KM5XmyiOu0Be38FOnkSFT/xXWCdRvUDJ7lD9YmRGtjkxgUBF+Fns2X0dJPXUyiK+CYpGn5sLC8jPhlg5QEuCJFSRR41HXocBkRLmpud6UN/Zo3iOeiFhM2iK1sYNX0=
before_deploy:
- python setup.py build sdist bdist_wheel
- if [ "x" == "$(grep $(git tag -l --points-at=HEAD) setup.py)x" ]; then echo 'new tag does not exist in setup.py; bailing!'; exit 1; else echo "tag found in setup.py"; fi
deploy:
  - provider: pypi
    user: atal
    skip_cleanup: true
    distributions: "sdist bdist_wheel"
    password:
      secure: "VJsATIRUu4gbAQq0E4ZpyVxBHm+Ly0lx34KmRHbLcSw8KHD/8myZgonSzJMMt9xzwV95e81TbSG+9O3Ri3yZwUCFk8alhuKUVkUVkUr3xt+8cPIlghPs7xEQSgpRDlNXKqk4qOsjDOanE6o/22xGZ9Ok+NExpU9afmCpw+d1db0DvoWH0FOjCMMHNmb46w8Uj8AAke7Oy7KncFjeIrglqdOZ3BUn3qEMicmPc8FfYI4Fwa3P5U0f9EaECDmeH7ksbjqz6LxOYXSrhb4uQmTPQClHOW5oIV+hjeMcXP20MAERZRQzhl6jWV4ZUgzkOmFglDqPwmMXOsf3EIn4fPooaZKQJD13pRMjoPC7GSU2F5fuFgKCIDXxL94/lY4dga6l7lEZLSkVuAmFVumkBe8njRmduFWMJqFo2zsaKtFL0M3DCSL5zPx846p/wZ3q8UX+edCZ6gt2hVA+IaoIOnIX1ioXIx/+lKCBc5U/U8NVpkB0THHZh14MBDvTH2aaI7xDImEwd8dVdx42MNie4y4xwM5TlOZhsgTMBAc2mtFrP/Fjt4NgSERcSbVZpAjMyVkypqMIaJyabbZ7IyTWLLTlWXwlOsur22D8LGvTWDwsg0MomT5lwslAUw+b4iyTUPavaJVpZIEWClY/dgqYi1thIf4e4GTFN4/uV+g3i1ujbTs="
    on:
      tags: true
      repo: ccpgames/pypackage
      condition: $TOXENV = py34
  - provider: releases
    api_key:
      secure: "sPKGWze1gfiBWDTWdEhaeYdvMpvw014OhZ8n/+txTtnmhUVO/xK/nS/QXJg8V5r7Q1P0/fsuVY3F8JKMwNSuVBa67kNDeU3sELh6lEaN5A4ajeZQutUBNRpJjYG3td2IGB2QyahcJC3dhVTRpP/0X9w7ktFFNFxOgfMg1UIctUW5m1dDfqZ/Ncio8XFGcWOvmjpvzjNqhw5cpBuMNtkcY6QgVDKSJTPVuYqYfejLf8oXx2o94YO029v+QrXHEiaQUbt+8PrkM0QpKrY+0tg0rqGq4yLGdEXeCuJj0zRX3txNPoirqpYAEmLAuVnN5r0n3rj4IF9rw5e1mnvNJDmY7yVuUnzk+2YFLhlWUKDsjHGEbtyP9fT01tvtvvZr1z5661SgPDONdVsajmt1dMfAINgDZuxw1C/s3SozOreL0ZUrb3Oz5il2bfDNPLd1hMOIL7aSybKl+CvyKpdoBSpFYQQxUsT76f8r6asaFnpiiq/2QPK9BbKeHNiZCQYLz1ZtMfAtXHnYA9kxmp5wf7iNhdLkfk3h281a88JyN52Dyi2bZXjCwjntvaMZWquAHvKRMMSQcOh+fxvlmyGweGxaAmRbcBfgi8nZt3vJ2E2HgyNY5MWXBh3GpEBchmeumUT0rFAntnKfciHUPhIujx3Z5Z6qrj23sNEaerzjUxg/b/k="
    file: "/home/travis/build/ccpgames/pypackage/dist/pypackage*.whl"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      condition: $TOXENV = py34
